import { Activity, Check, ChevronDown, Circle, Edit3, History, Lock, Plus, RefreshCw, Save, Settings2, Shield, ToggleLeft, ToggleRight, Users, X } from "lucide-react";
import { useMemo, useState } from "react";
import { trpc } from "@/lib/trpc";

const formatTime = (value: string) => new Date(value).toLocaleString([], { dateStyle: "medium", timeStyle: "short" });
const tabs = [{ id: "users", label: "Users", icon: Users }, { id: "connectors", label: "Connectors", icon: Activity }, { id: "rules", label: "Routing rules", icon: Settings2 }, { id: "audit", label: "Audit log", icon: History }];

export default function Admin() {
  const [tab, setTab] = useState("users");
  const overview = trpc.admin.overview.useQuery(undefined, { refetchOnWindowFocus: false });
  const toggle = trpc.admin.toggleConnector.useMutation({ onSuccess: () => overview.refetch() });
  const updateRule = trpc.admin.updateRule.useMutation({ onSuccess: () => overview.refetch() });
  const data = overview.data?.data;
  const [editingRule, setEditingRule] = useState<string | null>(null);
  const [draftDepartments, setDraftDepartments] = useState<string[]>([]);
  const connectorCount = data?.departments.filter((item) => item.connectorStatus === "UP").length ?? 0;
  const startEdit = (id: string, departments: string[]) => { setEditingRule(id); setDraftDepartments(departments); };
  const saveRule = (rule: any) => { updateRule.mutate({ ...rule, departments: draftDepartments }); setEditingRule(null); };
  return <div className="page-container admin-page"><div className="page-heading dashboard-heading"><div><span className="section-label">Admin workspace / Platform control</span><h1>Keep the service layer dependable.</h1><p>Manage who can act, how requests route, and whether each connector is ready to receive work.</p></div><div className="admin-health"><span className="health-ring"><Activity size={18} /></span><div><strong>{connectorCount}/3 connectors healthy</strong><small>Last system check just now</small></div></div></div><div className="admin-tabs">{tabs.map(({ id, label, icon: Icon }) => <button key={id} className={tab === id ? "admin-tab active" : "admin-tab"} onClick={() => setTab(id)}><Icon size={16} />{label}{id === "audit" && <span className="tab-count">{data?.auditLog.length ?? 0}</span>}</button>)}</div>{overview.isLoading ? <div className="loading-state"><RefreshCw className="spin" size={22} /> Loading controls…</div> : <div className="admin-content">{tab === "users" && <UsersTab users={data?.users ?? []} />}{tab === "connectors" && <ConnectorsTab departments={data?.departments ?? []} toggle={toggle} />}{tab === "rules" && <RulesTab rules={data?.rules ?? []} departments={data?.departments ?? []} editingRule={editingRule} draftDepartments={draftDepartments} setDraftDepartments={setDraftDepartments} startEdit={startEdit} saveRule={saveRule} />}{tab === "audit" && <AuditTab entries={data?.auditLog ?? []} />}</div>}<div className="admin-readonly-note"><Lock size={14} /><span>Admin changes are logged automatically. Audit entries are append-only and cannot be edited or deleted.</span></div></div>;
}

function UsersTab({ users }: { users: any[] }) { return <div className="admin-panel"><div className="panel-title-row"><div><span className="section-label">Access directory</span><h2>Users and assignments</h2><p>Demo identities are seeded for each SANYOG role.</p></div><button className="button button-outline small-button"><Plus size={14} /> Invite user</button></div><div className="admin-table"><div className="admin-table-head"><span>User</span><span>Role</span><span>Department</span><span>Status</span><span /></div>{users.map((user) => <div className="admin-table-row" key={user.id}><div className="admin-user"><span className="avatar">{user.name.slice(0, 1)}</span><div><strong>{user.name}</strong><small>{user.email}</small></div></div><span className={`role-badge ${user.role}`}>{user.role}</span><span>{user.department ?? "—"}</span><span className="active-state"><Circle size={8} fill="currentColor" /> {user.status}</span><button className="icon-button"><Edit3 size={15} /></button></div>)}</div></div>; }

function ConnectorsTab({ departments, toggle }: { departments: any[]; toggle: any }) { return <div className="admin-panel"><div className="panel-title-row"><div><span className="section-label">Adapter registry</span><h2>Connector health</h2><p>Toggle a connector to simulate the full request failure path.</p></div><span className="connector-legend"><Circle size={9} fill="currentColor" /> Live status</span></div><div className="connector-admin-grid">{departments.map((department) => <div className="connector-admin-card" key={department.id}><div className="connector-admin-top"><div className="connector-avatar" style={{ background: `${department.accent}16`, color: department.accent }}>{department.shortName}</div><span className={`connector-status ${department.connectorStatus.toLowerCase()}`}><Circle size={8} fill="currentColor" /> {department.connectorStatus}</span></div><h3>{department.name}</h3><p>{department.description}</p><div className="connector-meta"><span>Last heartbeat</span><strong>{new Date(department.lastHeartbeat).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</strong></div><div className="connector-controls"><button className={department.connectorStatus === "UP" ? "connector-toggle selected" : "connector-toggle"} onClick={() => toggle.mutate({ department: department.name, status: "UP" })}><Circle size={9} fill="currentColor" /> Up</button><button className={department.connectorStatus === "DELAYED" ? "connector-toggle selected delayed" : "connector-toggle"} onClick={() => toggle.mutate({ department: department.name, status: "DELAYED" })}><Circle size={9} fill="currentColor" /> Delayed</button><button className={department.connectorStatus === "DOWN" ? "connector-toggle selected down" : "connector-toggle"} onClick={() => toggle.mutate({ department: department.name, status: "DOWN" })}><Circle size={9} fill="currentColor" /> Down</button></div></div>)}</div></div>; }

function RulesTab({ rules, departments, editingRule, draftDepartments, setDraftDepartments, startEdit, saveRule }: any) { return <div className="admin-panel"><div className="panel-title-row"><div><span className="section-label">Routing engine</span><h2>Request type → departments</h2><p>Citizen selections are validated against these active rules before dispatch.</p></div><button className="button button-outline small-button"><Plus size={14} /> Add rule</button></div><div className="rules-table"><div className="rules-head"><span>Request type</span><span>Eligible departments</span><span>State</span><span /></div>{rules.map((rule: any) => <div className="rules-row" key={rule.id}><strong>{rule.requestType}</strong><div className="rule-departments">{editingRule === rule.id ? departments.map((department: any) => <label className="rule-check" key={department.id}><input type="checkbox" checked={draftDepartments.includes(department.name)} onChange={() => setDraftDepartments((current: string[]) => current.includes(department.name) ? current.filter((name) => name !== department.name) : [...current, department.name])} /><span>{department.shortName}</span></label>) : rule.departments.map((department: string) => <span key={department}>{department}</span>)}</div><span className={rule.active ? "active-state" : "muted-state"}><Circle size={8} fill="currentColor" /> {rule.active ? "Active" : "Paused"}</span>{editingRule === rule.id ? <button className="icon-button bordered" onClick={() => saveRule(rule)}><Save size={15} /></button> : <button className="icon-button bordered" onClick={() => startEdit(rule.id, rule.departments)}><Edit3 size={15} /></button>}</div>)}</div></div>; }

function AuditTab({ entries }: { entries: any[] }) { return <div className="admin-panel"><div className="panel-title-row"><div><span className="section-label">Immutable history</span><h2>Audit log</h2><p>Every submission, connector outcome, and admin action is recorded.</p></div><span className="readonly-chip"><Lock size={13} /> Read only</span></div><div className="audit-list">{entries.map((entry) => <div className="audit-row" key={entry.id}><div className="audit-icon"><History size={15} /></div><div className="audit-main"><strong>{entry.action.replaceAll("_", " ")}</strong><span>{entry.metadata}</span></div><div className="audit-meta"><strong>{entry.user}</strong><span>{formatTime(entry.timestamp)}</span></div></div>)}</div></div>; }
